new Vue({
  el:"#app",
  data:{
    items:[
      {
        name:"กาแฟ",
        price:15,
        url:"http://placehold.it/400x400",
        active:false
      },
      {
        name:"เครื่องซักผ้า",
        price:500,
        url:"http://placehold.it/400x400",
        active:false
      },
      {
        name:"หนังสือการ์ตูน",
        price:250,
        url:"http://placehold.it/400x400",
        active:false
      },
    ]
  }
})
